const ERROR_CODE_EMAIL_NOT_VERIFY = "e_1003";
const ERROR_CODE_EMAIL_VERIFY_TOKEN_EXP = "e_1002";
const ERROR_CODE_WRONG_USERNAME_OR_PASSWORD = "e_1001";
const ERROR_CODE_NO_MWS_ACCOUNT = "e_1004";
const ERROR_CODE_VERIFY_PURCHASE_APPLE_ID_USING_FOR_OTHER_ACCOUNT = "e_1006";
const ERROR_CODE_NO_MWS_TOKEN = "e_1007";